name: mobile_intranet
description: Intranet epitech mobile

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.1.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  http: 0.12.0+2
  flutter_webview_plugin:
  flutter_cache_manager: ^1.1.2
  shared_preferences:
  font_awesome_flutter: 8.4.0
  percent_indicator: ^2.1.0
  outline_material_icons: ^0.1.0
  flutter_sparkline: ^0.1.0
  html: ^0.14.0+3
  calendar_views: ^0.5.2
  intl: ^0.15.8
  android_alarm_manager: ^0.4.5+3
  background_fetch: ^0.5.0
  flutter_local_notifications:
  cached_network_image: ^2.0.0
  timezone: 0.5.6

  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.     36CFF5
  #cupertino_icons: ^0.1.2

  json_annotation: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  flutter_spinkit: ^4.0.0
  add_2_calendar: ^1.3.1
  flutter_svg: 0.15.0


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: Sarabun
      fonts:
        - asset: assets/fonts/Sarabun/Sarabun-Regular.ttf
        - asset: assets/fonts/Sarabun/Sarabun-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sarabun/Sarabun-Thin.ttf
          weight: 100
        - asset: assets/fonts/Sarabun/Sarabun-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Sarabun/Sarabun-Light.ttf
          weight: 300
        - asset: assets/fonts/Sarabun/Sarabun-Medium.ttf
          weight: 500
        - asset: assets/fonts/Sarabun/Sarabun-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Sarabun/Sarabun-ExtraBold.ttf
          weight: 700


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
