library ConfigurationKeys;

const String CONFIG_KEY_SCHEDULE_FR = "key_config_schedule_fr";
const String CONFIG_KEY_SCHEDULE_ONLY_REGISTERED_MODULES = "key_config_schedule_only_registered_modules";
const String CONFIG_KEY_SCHEDULE_ONLY_REGISTERED_SESSIONS = "key_config_schedule_only_registered_sessions";